
#General settings of Crash Assistant mod.
[general]
	#Link which will be opened in browser on request_help_button pressed.
	help_link = "https://discord.gg/PXS33fEM2e"
	#Show gui on minecraft crashed on modloading and FML error screen displayed.
	show_on_fml_error_screen = true
	#Close old CrashAssistantApp if it's still running when starting a new instance of Minecraft, to avoid confusing player with window from old crash.
	kill_old_app = true
	#List of blacklisted log files. This files won't show in GUI logs list.
	blacklisted_logs = ["CrashAssistant: latest.log"]
	#If options.txt doesn't exist, the default language will be used.
	default_lang = "en_us"

#Here you can configure debug options for easier configuration of the mod.
[debug]
	#Setting this value to one of listed here, will crash the game in order to show/debug gui.
	#NONE - default value, no crash. You can always crash game by holding vanilla F3+C keybind.
	#MIXIN_SETUP - will crash game on Mixin setup. Crash report not generated.
	#MOD_LOADING - will crash game on load of this mod. Can be used to show FML error screen. Crash report generated.
	#GAME_STARTED - will crash game on first tick of TitleScreen. Crash report generated.
	crash_game_on_event = "NONE"

#Here you can change text of lang placeHolders.
#You can change any text in lang files.
#You don't need to modify jar. You can change it in config/crash_assistant/lang. For more info read README.md file located where.
[text]
	#$SUPPORT_NAME$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "gui.request_help_button": "request help in $SUPPORT_NAME$"
	support_name = "Modded Minecraft Discord"
	#$SUPPORT_PLACE$ in lang files will be replaced with this value.
	support_place = "player_help channel"
	#$MODPACK_NAME$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "gui.title_crashed_with_report": "Oops, $MODPACK_NAME$ crashed!"
	modpack_name = "Minecraft"

#Settings of modlist feature.
#Adds in generated msg block about which mods modpack user added/removed/updated.
[modpack_modlist]
	#Enable feature.
	enabled = true
	#UUID's of players, who considered as modpack creator.
	#Only this players can overwrite modlist.json
	#If this feature is enabled and this array is empty, will be appended with UUID of current player.
	modpack_creators = ["00d5f600d47041fbbc1e7861382e204d"]
	#If enabled, modlist.json will be overwritten on every launch(mod loading),
	#then game is launched by modpack creator.
	#So you won't forget to save it before publishing.
	auto_update = true

