
[Vanilla]

	[Vanilla.metal_ores]
		#If mining ores that normally drop raw ores should grant XP
		"Experienced metal" = true

	[Vanilla.farmland]
		#Whether farmland can be untilled by sneak-right clicking them with a hoe
		"Untillable Farmland" = true

	[Vanilla.crops]
		#If all blocks that are crops should drop experience.
		"Experienced Crops" = true
		#Minimum XP a crop block will drop when broken.
		"Minimum Crop XP" = 0
		#Maximum XP a crop block will drop when broken.
		"Maximum Crop XP" = 1

	[Vanilla.dispensers]
		#If dispensers should be able to dispense into cauldrons
		"Dispenser Cauldrons" = true

[atmospheric]

	[atmospheric.Oranges]
		#If oranges can no longer be jumped on to be broken and to create a vapor cloud
		"Normal Oranges" = true

[farmersdelight]

	[farmersdelight."Knife Enchantments"]
		#If knives should no longer receive the silk touch and efficiency from the enchanting table
		"Unbloated Knife Enchantments" = true

[nethersdelight]

	[nethersdelight.fungus_colonies]
		#If fungus colonies should grow on normal rich soil instead of soul rich soil
		"Rich Fungus" = true

[supplementaries]

	[supplementaries.quivers]
		#If processing a quiver in a cutting board will eject all the arrows in that quiver
		"Realistic Quivers" = true

[anchor]

	[anchor."epilogue Disc"]
		#If striking a jukebox with lightning with a filled disc inside will change that disc to Epilogue
		"AWESOME epilogue disc" = true

