
[dyson_sphere]
	#A list of dimensions where the Dyson Sphere should not be accessible. Add dimensions in the format 'minecraft:the_end', 'ad_astra:mercury'. Default: 'minecraft:the_end', 'minecraft:the_nether
	dimensionBlacklist = ["minecraft:the_end", "minecraft:the_nether"]
	#If the dimensionBlacklist should be used as a whitelist instead, Default: false
	dimensionIsWhitelist = false

	[dyson_sphere.ds_energy_receiver]
		#The upper limit of heat capacity of the dyson sphere energy receiver. 0-1.7976931348623157E308. Default 1700
		#Range: 0.0 ~ 1.7976931348623157E308
		dsEnergyReceiverMaxHeat = 1700.0

	[dyson_sphere.heat_exchanger]
		#The upper limit of heat capacity of the heat exchanger. 0-1.7976931348623157E308. Default 1700
		#Range: 0.0 ~ 1.7976931348623157E308
		heatExchangerMaxHeat = 1700.0
		#The lower limit of heat required for the heat exchanger to start working. 0-1.7976931348623157E308. Default 450
		#Range: 0.0 ~ 1.7976931348623157E308
		heatExchangerMinHeat = 450.0
		#The base amount of water converted to steam per tick (1mB water -> 10mB steam) when working. 0-4000. Default 5
		#Range: 0 ~ 4000
		heatExchangerBaseProduce = 5
		#The bonus amount of water converted to steam per tick (1mB water -> 10mB steam) per bonusHeat over minHeat. 0-4000. Default 1
		#Range: 0 ~ 4000
		heatExchangerBonusProduce = 1
		#The bonus heat required above the minHeat per bonusProduce to be produced. 0-1.7976931348623157E308. Default 50
		#Range: 0.0 ~ 1.7976931348623157E308
		heatExchangerBonusHeat = 50.0
		#The capacity of the internal fluid Tank (input and output) of the heat exchanger. 1-2147483647. Default 4000
		#Range: > 1
		heatExchangerFluidCapacity = 4000
		#The heat consumption per 1mB of water converted to 10mB of steam. 0-1.7976931348623157E308. Default 2.5
		#Range: 0.0 ~ 1.7976931348623157E308
		heatExchangerHeatConsumption = 2.5

	[dyson_sphere.heat_generator]
		#The upper limit of heat capacity of the heat generator. 0-1.7976931348623157E308. Default 1700
		#Range: 0.0 ~ 1.7976931348623157E308
		heatGeneratorMaxHeat = 1700.0
		#The energy capacity of the heat generator. 1-2147483647. Default 25000
		#Range: > 1
		heatGeneratorEnergyCapacity = 25000
		#The minimum heat difference required to generate RF. Production is per min heat difference
		#Range: 0.0 ~ 10000.0
		heatGeneratorMinHeatDif = 25.0
		#The amount of RF generated per minimum heat difference between adjacent heat containers. 0-2147483647. Default 1
		#Range: > 0
		heatGeneratorEnergyGenerated = 1

	[dyson_sphere.heat_pipe]
		#The upper limit of heat capacity of the heat pipe. 0-1.7976931348623157E308. Default 1950
		#Range: 0.0 ~ 1.7976931348623157E308
		heatPipeMaxHeat = 1950.0

	[dyson_sphere.railgun]
		#The energy required for the railgun to launch a single item. 0-2147483647. Default 90000
		#Range: > 0
		railgunLaunchEnergy = 90000
		#The energy capacity of the railgun. Must be bigger then the launchEnergy for the railgun to work. 1-2147483647. Default 150000
		#Range: > 1
		railgunEnergyCapacity = 150000

	[dyson_sphere.solar_capsule]
		#The energy a single solar capsule provides per tick once added to the dyson sphere. 0-2147483647. Default 10
		#Range: > 0
		solarCapsuleEnergyProvided = 10
		#The dyson sphere completion a single solar capsule adds. 0.0-1.0. Default 0.00001
		#Range: 0.0 ~ 1.0
		solarCapsuleCompletion = 1.0E-5

