
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.createdieselgenerators]
			chip_wood = false

		[types.wood_type.habitat]
			fairy_ring_mushroom = true

		[types.wood_type.quark]
			azalea = false
			ancient = true
			blossom = false

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.enhanced_mushrooms]
			mushroom = true

		[types.wood_type.enlightened_end]
			indigo = true
			cerulean = true

		[types.wood_type.spawn]
			rotten = true

		[types.wood_type.goodending]
			muddy_oak = true
			cypress = false

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.netherdungeons]
			ginger = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = false
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.wood_type.biomemakeover]
			blighted_balsa = false
			willow = false
			swamp_cypress = false
			ancient_oak = false

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.hexcasting]
			edified = true

		[types.wood_type.flying_stuff]
			glaciated = false
			lavic = false

		[types.wood_type.aromatic]
			cinnamon = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.unusualend]
			chorus_cane = true

	[types.cake]

		[types.cake.bountifulfares]
			cocoa_cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.exquisito]
			chorus_cake = true
			ether_bulb_cake = true
			jelly_ring_cake = true
			nightshade_berry_cake = true
			zure_berry_cake = true

		[types.cake.natures_spirit]
			cheese_block = true

		[types.cake.mynethersdelight]
			magma_cake = true

		[types.cake.farmersrespite]
			coffee_cake = true

		[types.cake.respiteful]
			green_tea_cake = true
			yellow_tea_cake = true
			black_tea_cake = true

	[types.leaves_type]

		[types.leaves_type.bountifulfares]
			apple = true
			flowering_apple = true
			orange = true
			flowering_orange = true
			lemon = true
			flowering_lemon = true
			plum = true
			flowering_plum = true
			hoary = true
			walnut = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.goodending]
			cypress = false
			dense_birch = false
			dense_dark_oak = false

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			yellow_blossom = false
			red_blossom = false

		[types.leaves_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			blue_wisteria = true
			pink_wisteria = true
			purple_wisteria = true
			part_white_wisteria = true
			part_blue_wisteria = true
			part_pink_wisteria = true
			part_purple_wisteria = true
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			yellow_larch = true
			mahogany = true
			saxaul = true
			frosty_redwood = true

		[types.leaves_type.biomemakeover]
			blighted_balsa = false
			willow = false
			swamp_cypress = false
			ancient_oak = false

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.hexcasting]
			amethyst_edified = true
			aventurine_edified = true
			citrine_edified = true

		[types.leaves_type.aromatic]
			cinnamon = true

	[types.stone_type]

		[types.stone_type.natures_spirit]
			travertine = true
			chert = true
			kaolin = true
			white_kaolin = true
			light_gray_kaolin = true
			gray_kaolin = true
			black_kaolin = true
			brown_kaolin = true
			red_kaolin = true
			orange_kaolin = true
			yellow_kaolin = true
			lime_kaolin = true
			green_kaolin = true
			cyan_kaolin = true
			light_blue_kaolin = true
			blue_kaolin = true
			purple_kaolin = true
			magenta_kaolin = true
			pink_kaolin = true

		[types.stone_type.flying_stuff]
			glaciated_skyrock = true
			mossy_glaciated_skyrock = true
			lavic_skyrock = true
			grimstone = false

		[types.stone_type.trials]
			chiseled_tuff = true

		[types.stone_type.immersive_weathering]
			snowy_stone = true
			sandy_stone = true

		[types.stone_type.ad_astra]
			moon_stone = true
			mars_stone = true
			mercury_stone = true
			venus_stone = true
			venus_sandstone = true
			glacio_stone = true
			permafrost = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.undergarden]
			depthrock = true
			shiverstone = true
			tremblecrust = true

		[types.stone_type.enlightened_end]
			palerock = true
			void_shale = true

		[types.stone_type.spelunkery]
			rock_salt = true
			polished_nephrite = true

		[types.stone_type.architects_palette]
			abyssaline = true
			hadaline = true
			myonite = true
			weeping_blackstone = true
			twisting_blackstone = true
			esoterrack = true
			onyx = true
			wardstone = true
			moonshale = true

		[types.stone_type.twigs]
			polished_tuff = true
			polished_calcite = true
			polished_schist = true
			polished_rhyolite = true
			polished_bloodstone = true
			silt = true

		[types.stone_type.sculkhorde]
			infested_mud = true
			infested_stone = true
			infested_blackstone = true

		[types.stone_type.biomemakeover]
			dried_peat = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.upgrade_aquatic]
			kelpy_cobblestone = true

		[types.stone_type.hexcasting]
			quenched_allay = false
			slate = true

		[types.stone_type.alexscaves]
			galena = true
			radrock = true
			abyssmarine = true
			guanostone = true

		[types.stone_type.netherdungeons]
			ominous_quartz = true
			polished_gilded_blackstone = true

		[types.stone_type.oreganized]
			glance = true

		[types.stone_type.quark]
			soul_sandstone = true
			permafrost = true
			limestone = true
			jasper = true
			shale = true
			myalite = true

		[types.stone_type.supplementaries]
			ash = true

		[types.stone_type.netherexp]
			soul_slate = true

		[types.stone_type.unusualend]
			polished_purpur = true
			gneiss = true
			gloopstone = true
			gloopslate = true
			warped_stone = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			board_slab = true
			boards = true
			board_wall = true

		[entries.wood_type.mighty_mail]
			mail_box = true

		[entries.wood_type.create]
			window = false
			window_pane = false

		[entries.wood_type.shutter]
			shutter = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = false
			post = true
			trapped_chest = false
			bookshelf = false
			chest = false
			stripped_post = true
			ladder = false

		[entries.wood_type.twigs]
			table = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = false
			leaf_carpet = false

		[entries.leaves_type.woodworks]
			leaf_pile = false

