
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.habitat]
				fairy_ring_mushroom = false

			[general.types.wood_type.enlightened_end]
				indigo = true
				cerulean = true

			[general.types.wood_type.spawn]
				rotten = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.architects_palette]
				twisted = true

			[general.types.wood_type.quark]
				azalea = false
				ancient = true
				blossom = true

			[general.types.wood_type.flying_stuff]
				glaciated = false
				lavic = false

			[general.types.wood_type.ad_astra]
				aeronos = true
				strophar = true
				glacian = true

			[general.types.wood_type.createdieselgenerators]
				chip_wood = false

			[general.types.wood_type.bountifulfares]
				hoary = true
				walnut = true

			[general.types.wood_type.autumnity]
				maple = true

			[general.types.wood_type.goodending]
				muddy_oak = true
				cypress = true

			[general.types.wood_type.upgrade_aquatic]
				driftwood = true
				river = true

			[general.types.wood_type.enhanced_mushrooms]
				mushroom = true

			[general.types.wood_type.mynethersdelight]
				powdery = true

		[general.types.leaves_type]

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.architects_palette]
				twisted = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.ad_astra]
				glacian = true

			[general.types.leaves_type.bountifulfares]
				apple = true
				flowering_apple = true
				orange = true
				flowering_orange = true
				lemon = true
				flowering_lemon = true
				plum = true
				flowering_plum = true
				hoary = true
				walnut = true

			[general.types.leaves_type.autumnity]
				maple = true
				yellow_maple = true
				orange_maple = true
				red_maple = true

			[general.types.leaves_type.goodending]
				cypress = true
				dense_birch = true
				dense_dark_oak = true

			[general.types.leaves_type.upgrade_aquatic]
				river = true

		[general.types.cake]

			[general.types.cake.createaddition]
				chocolate_cake = true
				honey_cake = true

			[general.types.cake.bountifulfares]
				cocoa_cake = true

			[general.types.cake.collectorsreap]
				lime_cake = true
				pomegranate_cake = true

			[general.types.cake.neapolitan]
				vanilla_cake = true
				chocolate_cake = true
				strawberry_cake = true
				banana_cake = true
				mint_cake = true
				adzuki_cake = true

			[general.types.cake.seasonals]
				pumpkin_cake = true
				sweet_berry_cake = true
				beetroot_cake = true

			[general.types.cake.exquisito]
				chorus_cake = true
				ether_bulb_cake = true
				jelly_ring_cake = true
				nightshade_berry_cake = true
				zure_berry_cake = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.create]
				window = false
				window_pane = false

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.architects_palette]
				boards = true
				board_stairs = true
				railing = true
				board_wall = true
				board_slab = true

			[general.entries.wood_type.quark]
				hollow_log = true
				vertical_planks = false
				post = true
				trapped_chest = false
				bookshelf = false
				chest = false
				stripped_post = true
				ladder = true

			[general.entries.wood_type.mighty_mail]
				mail_box = true

			[general.entries.wood_type.woodworks]
				trapped_chest = true
				boards = false
				chest = true
				beehive = true
				bookshelf = true
				chiseled_bookshelf = true
				ladder = true

			[general.entries.wood_type.shutter]
				shutter = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = false

			[general.entries.leaves_type.woodworks]
				leaf_pile = false

