
["Configs for Happy Pride Moth! [Forge]"]
	#Determines whether or not pride variants for moths spawn naturally outside of Pride Month
	#Default value: false
	"Spawn Pride Variants Outside of Pride Month" = false
	#Determines the default value for the rare, golden moth variant
	#The integer used will be used like this: 1 out of <value> chance
	#Default value: 240
	"Chance of a Moth Spawning as the Rare Variant" = 240
	#Determines the default value for the rare, golden moth variant during moth week (last week of July)
	#The integer used will be used like this: 1 out of <value> chance
	#Default value: 120
	"Chance of a Moth Spawning as the Rare Variant During Moth Week" = 120

