
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				cow = true
				pig = true
				bat = true
				sheep = true
				arrow = true
				item = true
				cod = true
				chicken = true
				dolphin = true
				tnt_minecart = true
				cat = true
				glow_squid = true
				bee = true
				chest_minecart = true
				squid = true
				egg = true
				wolf = true
				potion = true
				experience_orb = true
				tropical_fish = true
				turtle = true
				axolotl = true
				painting = true
				item_frame = true
				firework_rocket = true
				llama = true
				furnace_minecart = true
				minecart = true
				rabbit = true
				villager = true
				spider = true
				skeleton = true
				cave_spider = true
				zombie = true
				enderman = true
				creeper = true
				guardian = true
				slime = true
				zombie_villager = true
				drowned = true
				witch = true
				pufferfish = true
				salmon = true
				silverfish = true
				horse = true
				iron_golem = true
				ocelot = true
				pillager = true
				vindicator = true
				armor_stand = true
				lightning_bolt = true
				husk = true
				area_effect_cloud = true
				magma_cube = true
				mule = true
				donkey = true
				wandering_trader = true
				trader_llama = true
				warden = true
				fishing_bobber = true
				fox = true
				polar_bear = true
				stray = true
				frog = true
				vex = true
				snow_golem = true
				illusioner = true
				zoglin = true
				elder_guardian = true
				wither_skeleton = true
				phantom = true
				hoglin = true
				parrot = true
				evoker_fangs = true
				trident = true
				evoker = true
				spectral_arrow = true
				endermite = true
				ghast = true
				ravager = true
				piglin = true
				piglin_brute = true
				zombified_piglin = true
				zombie_horse = true
				llama_spit = true
				snowball = true
				goat = true
				allay = true
				hopper_minecart = true
				strider = true
				shulker = true
				ender_pearl = true
				boat = true
				leash_knot = true
				skeleton_horse = true
				panda = true
				glow_item_frame = true
				camel = true

			[light_sources.settings.entities.alexsmobs]
				crow = true
				cockroach = true
				flying_fish = true
				fly = true
				seal = true
				grizzly_bear = true
				lobster = true
				seagull = true
				underminer = true
				flutter = true
				leafcutter_ant = true
				emu = true
				rattlesnake = true
				toucan = true
				capuchin_monkey = true
				kangaroo = true
				skunk = true
				roadrunner = true
				hummingbird = true
				blue_jay = true
				tiger = true
				terrapin = true
				potoo = true
				catfish = true
				sugar_glider = true
				skelewag = true
				raccoon = true
				murmur_head = true
				murmur = true
				orca = true
				centipede_head = true
				centipede_tail = true
				centipede_body = true
				rain_frog = true
				rocky_roller = true
				gelada_monkey = true
				tasmanian_devil = true
				bison = true
				crocodile = true
				devils_hole_pupfish = true
				farseer = true
				rhinoceros = true
				gazelle = true
				platypus = true
				bald_eagle = true
				skreecher = true
				snow_leopard = true
				frilled_shark = true
				cosmic_cod = true
				comb_jelly = true
				banana_slug = true
				moose = true
				tusklin = true
				elephant = true
				alligator_snapping_turtle = true
				anaconda_part = true
				anaconda = true
				blobfish = true
				giant_squid = true
				cachalot_whale = true
				dropbear = true
				crimson_mosquito = true
				laviathan = true
				bone_serpent = true
				bone_serpent_part = true
				stradpole = true
				straddler = true
				enderiophage = true
				spectre = true
				endergrade = true
				komodo_dragon = true
				gorilla = true
				mudskipper = true
				caiman = true
				mantis_shrimp = true
				triops = true
				tarantula_hawk = true
				mimic_octopus = true
				guster = true
				maned_wolf = true

			[light_sources.settings.entities.spawn]
				hamster = true
				ant = true
				tuna = true
				angler_fish = true
				snail = true
				seahorse = true

			[light_sources.settings.entities.enemyexpansion]
				meature = true
				slugger = true
				huntsman = true
				sprinter = true
				goblin = true
				troll = true
				vampire = true
				vampbiter = true
				wasp = true
				vampflyer = true
				equestrian = true
				tarantula = true
				scorpion = true
				starved = true
				botfly = true
				flutterfly = true
				ladybug = true

			[light_sources.settings.entities.spelunkers_charm]
				sound_entity = true
				tremor_handler = true
				projectile_thrown_rock = true
				projectile_thrown_deepslate_rock = true

			[light_sources.settings.entities.quark]
				torch_arrow = true
				glass_frame = true
				shiba = true
				toretoise = true
				wraith = true
				forgotten = true
				stoneling = true
				foxhound = true

			[light_sources.settings.entities.beansbackpacks]
				backpack = true
				ender_backpack = true
				winged_backpack = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true
				glare = true
				copper_golem = true
				mauler = true
				moobloom = true
				tuff_golem = true
				iceologer = true
				wildfire = true

			[light_sources.settings.entities.sullysmod]
				lanternfish = true
				tortoise = true
				bouldering_zombie = true
				jungle_spider = true

			[light_sources.settings.entities.species]
				deepfish = true
				birt = true
				roombug = true
				wraptor = true

			[light_sources.settings.entities.corpse]
				corpse = true

			[light_sources.settings.entities.alexscaves]
				beholder_eye = true
				gloomoth = true
				subterranodon = true
				nuclear_explosion = true
				dinosaur_spirit = true
				extinction_spear = true
				quarry_smasher = true
				vallumraptor = true
				tremorsaurus = true
				grottoceratops = true
				relicheirus = true
				trilocaris = true
				raycat = true
				gammaroach = true
				radgill = true
				nucleeper = true
				underzealot = true
				corrodent = true
				vesper = true

			[light_sources.settings.entities.habitat]
				passerine = true
				pooka = true

			[light_sources.settings.entities.galosphere]
				sparkle = true
				spectre = true

			[light_sources.settings.entities.cloudstorage]
				balloon = true
				balloon_tie = true
				badloon = true
				bloviator = true
				balloon_buddy = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true

			[light_sources.settings.entities.create]
				super_glue = true
				stationary_contraption = true
				contraption = true

			[light_sources.settings.entities.flying_stuff]
				sky_automaton = true
				sky_automaton_boss = true
				projectile_smoke_flower_proj = true

			[light_sources.settings.entities.sihywtcamd]
				cobweb = true

			[light_sources.settings.entities.snowyspirit]
				gingerbread_golem = true
				sled = true

			[light_sources.settings.entities.sleep_tight]
				bed_entity = true

			[light_sources.settings.entities.surface]
				rhino = true
				grizzly_bear = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.black_hole]
				black_hole = true

			[light_sources.settings.entities.labels]
				label = true

			[light_sources.settings.entities.gipples_galore]
				gipple = true

			[light_sources.settings.entities.geologicexpansion]
				duck = true

			[light_sources.settings.entities.ad_astra]
				glacian_ram = true
				tier_4_rocket = true
				lander = true
				zombified_pygro = true
				corrupted_lunarian = true
				star_crawler = true
				lunarian = true
				martian_raptor = true
				pygro = true
				mogler = true

			[light_sources.settings.entities.undergarden]
				forgotten_guardian = true
				smog_mog = true
				forgotten = true
				blisterbomb = true
				brute = true
				mog = true
				scintling = true
				rotwalker = true
				gloomper = true
				stoneborn = true
				dweller = true
				rotling = true
				rotbeast = true
				gwibling = true
				nargoyle = true
				gwib = true
				muncher = true
				sploogie = true

			[light_sources.settings.entities.immersive_aircraft]
				gyrodyne = true

			[light_sources.settings.entities.sculkhorde]
				sculk_enderman = true
				sculk_phantom = true
				sculk_ravager = true
				sculk_vindicator = true
				sculk_hatcher = true
				sculk_creeper = true
				sculk_spitter = true
				sculk_zombie = true
				sculk_mite = true
				sculk_mite_aggressor = true
				cursor_surface_infector = true
				sculk_spore_spewer = true
				sculk_acidic_projectile = true
				purification_flask_projectile = true
				cursor_surface_purifier = true
				infestation_purifier = true
				custom_item_projectile = true

			[light_sources.settings.entities.enchancement]
				brimstone = true
				torch = true
				ice_shard = true

			[light_sources.settings.entities.weather2]
				lightning_bolt = true

			[light_sources.settings.entities.cnc]
				chupacabra = true
				cougar = true
				wolverine = true
				wendigo = true
				ringtail = true
				greywolf = true
				coyote = true
				whitetail = true
				elk = true
				skinwalker = true
				bewitched_greywolf = true

			[light_sources.settings.entities.conjuring]
				soul_projectile = true

			[light_sources.settings.entities.polars_mad_tweaks]
				silverfish = true

			[light_sources.settings.entities.enlightened_end]
				gloop = true
				fumesplat = true
				stalker = true
				ooze_bubble = true
				void_leviathan = true

			[light_sources.settings.entities.outer_end]
				sinker = true
				sinker_laser = true

			[light_sources.settings.entities.cold_sweat]
				chameleon = true

			[light_sources.settings.entities.crabbersdelight]
				crab = true

			[light_sources.settings.entities.apugli]
				custom_projectile = true
				custom_area_effect_cloud = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

