
[behaviour]
	#This section determines the behaviour of the Weeping Angels.
	#Range for player visibility check.
	#Range: 1 ~ 100
	stalk_range = 65
	#Allow angels to break light-emitting blocks?
	block_breaking = false

[damage]
	#Type of hurt inflicted by angels.
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "PICKAXE_AND_GENERATOR"

[teleporting]
	#Range for teleportation.
	#Range: > 1
	teleport_range = 400
	#Allow teleporting across dimensions?
	interdimensional_teleporting = true
	#Allow Angel theft?
	angel_theft = false
	#Chance of teleportation occurring.
	#Range: 1 ~ 100
	teleport_chance = 50
	#Dimensions where teleportation is banned.
	banned_dimensions = ["minecraft:the_end", "ad_astra:earth_orbit", "ad_astra:glacio", "ad_astra:glacio_orbit", "ad_astra:mars", "ad_astra:mars_orbit", "ad_astra:mercury", "ad_astra:mercury_orbit", "ad_astra:moon", "ad_astra:moon_orbit", "ad_astra:venus", "ad_astra:venus_orbit", "cosmos:alpha_system", "cosmos:b_1400_centauri", "cosmos:earth_moon", "cosmos:europa_lands", "cosmos:gaia_bh_1", "cosmos:glacio_lands", "cosmos:j_1407blands", "cosmos:j_1900", "cosmos:jupiterlands", "cosmos:marslands", "cosmos:mercury_wasteland", "cosmos:neptune_lands", "cosmos:plutowastelands", "cosmos:saturn_lands", "cosmos:solar_system", "cosmos:uranus_lands", "cosmos:venuslands", "flying_stuff:under_ground"]

